# Generated by Django 6.0.5 on 2026-06-15 14:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racas', to='pets.especie')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
                'ordering': ['especie', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raca', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('idade', models.PositiveIntegerField(help_text='Idade em anos ou meses', validators=[django.core.validators.MinValueValidator(0)])),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso em kg', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('alergias', models.TextField(blank=True, null=True)),
                ('castrado', models.BooleanField(default=False)),
                ('medicamentos_continuos', models.TextField(blank=True, null=True)),
                ('codigo_vinculo', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('especie_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pets.especie')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
                ('raca_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pets.raca')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='raca',
            constraint=models.UniqueConstraint(fields=('especie', 'nome'), name='unique_breed_per_species'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['tutor', 'created_at'], name='pets_pet_tutor_i_f7e4b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.CheckConstraint(condition=models.Q(('idade__gte', 0)), name='pet_age_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.CheckConstraint(condition=models.Q(('peso__gte', 0)), name='pet_weight_non_negative'),
        ),
    ]
