# Generated by Django 6.0.5 on 2026-06-15 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_filhote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='unidade_idade',
            field=models.CharField(choices=[('anos', 'Anos'), ('meses', 'Meses'), ('semanas', 'Semanas')], default='anos', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='idade',
            field=models.PositiveIntegerField(help_text='Valor numérico da idade', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
