# Generated by Django 6.0.5 on 2026-07-02 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_is_filhote_pet_unidade_idade_alter_pet_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='meta_peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meta de peso em kg', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='peso',
            field=models.DecimalField(decimal_places=2, help_text='Peso atual em kg', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
