# Generated by Django 6.0.5 on 2026-06-15 14:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=200)),
                ('clinica', models.CharField(blank=True, max_length=100, null=True)),
                ('veterinario', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField(db_index=True)),
                ('hora', models.TimeField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], db_index=True, default='agendado', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-data', '-hora'],
                'indexes': [models.Index(fields=['pet', 'data'], name='health_cons_pet_id_4d4602_idx')],
            },
        ),
        migrations.CreateModel(
            name='EstadoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_notificacao', models.CharField(db_index=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_lidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de Leitura de Notificação',
                'verbose_name_plural': 'Estados de Leitura de Notificação',
                'unique_together': {('user', 'chave_notificacao')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_index=True, max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Histórico de Saúde',
                'verbose_name_plural': 'Históricos de Saúde',
                'ordering': ['-data', '-created_at'],
                'indexes': [models.Index(fields=['pet', 'data'], name='health_hist_pet_id_a73ed1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('ultima_data', models.DateField()),
                ('proxima_data', models.DateField(blank=True, db_index=True, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('dose', models.CharField(blank=True, max_length=50, null=True)),
                ('clinica', models.CharField(blank=True, max_length=100, null=True)),
                ('veterinario', models.CharField(blank=True, max_length=100, null=True)),
                ('lembrete_ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Vacina',
                'verbose_name_plural': 'Vacinas',
                'ordering': ['proxima_data', 'ultima_data'],
                'indexes': [models.Index(fields=['pet', 'proxima_data'], name='health_vaci_pet_id_f20680_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('proxima_data__gte', models.F('ultima_data')), ('proxima_data__isnull', True), _connector='OR'), name='vaccine_next_date_after_last_date')],
            },
        ),
        migrations.CreateModel(
            name='Vermifugo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome_produto', models.CharField(max_length=100)),
                ('ultima_data', models.DateField()),
                ('proxima_data', models.DateField(blank=True, db_index=True, null=True)),
                ('frequencia', models.CharField(blank=True, max_length=50, null=True)),
                ('dosagem', models.CharField(blank=True, max_length=50, null=True)),
                ('peso_momento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('clinica', models.CharField(blank=True, max_length=100, null=True)),
                ('veterinario', models.CharField(blank=True, max_length=100, null=True)),
                ('lembrete_ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vermifugos', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Vermífugo',
                'verbose_name_plural': 'Vermífugos',
                'ordering': ['proxima_data', 'ultima_data'],
                'indexes': [models.Index(fields=['pet', 'proxima_data'], name='health_verm_pet_id_4a8937_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('proxima_data__gte', models.F('ultima_data')), ('proxima_data__isnull', True), _connector='OR'), name='deworming_next_date_after_last_date')],
            },
        ),
    ]
