# Generated by Django 6.0.5 on 2026-07-02 22:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
        ('pets', '0002_pet_is_filhote_pet_unidade_idade_alter_pet_idade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Peso',
                'verbose_name_plural': 'Pesos',
                'ordering': ['-data', '-created_at'],
                'indexes': [models.Index(fields=['pet', 'data'], name='health_peso_pet_id_b51671_idx')],
            },
        ),
    ]
