# Generated by Django 6.0.5 on 2026-07-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='peso',
            name='meta_atingida',
            field=models.BooleanField(default=False),
        ),
    ]
