# Generated by Django 6.0.5 on 2026-07-03 00:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_peso_meta_atingida'),
        ('pets', '0003_pet_meta_peso_alter_pet_peso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('dosagem', models.CharField(blank=True, max_length=50, null=True)),
                ('frequencia', models.CharField(blank=True, max_length=50, null=True)),
                ('data_inicio', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('data_fim', models.DateField(blank=True, db_index=True, null=True)),
                ('lembrete_ativo', models.BooleanField(default=True)),
                ('concluido', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['-data_inicio'],
                'indexes': [models.Index(fields=['pet', 'data_inicio'], name='health_medi_pet_id_aa4376_idx')],
            },
        ),
    ]
